### ISSUE TITLE
setDI wrong declaration

### ISSUE THREAD

**Issue by stefanchiriac** [Zazza/phalcon2-debug-widget#3]
Fatal error: Declaration of PDW\DebugWidget::setDI() must be compatible with Phalcon\Di\InjectionAwareInterface::setDI(Phalcon\DiInterface $dependencyInjector) in /home/gatz/www/cms/app/vendor/zazza/phalcon-debug-widget/src/PDW/DebugWidget.php on line 11

Instead of 
`public function setDI($di)`
put
`public function setDI(\Phalcon\DiInterface $di)`

Also, if the vendor directory is behind public folder, it won't display anything

**Comment by Zazza** [comment]
you don't confuse:
https://github.com/Zazza/phalcon-debug-widget for 1.x.x versions
and
https://github.com/Zazza/phalcon2-debug-widget fot 2 version framework ?

I checked - everything normally works

vendor a directory lies there where is specified in composer.json if to establish from https://packagist.org/packages/zazza/phalcon2-debug-widget (in README it isn't correctly written, I will correct now)

**Comment by stefanchiriac** [comment]
ahh.. you're right. I got the wrong package from composer.
Thank you.

**Comment by stefanchiriac** [comment]
by the way... you should include the base path too when adding resources.
This doesn't work if the base path is /something/ like in my case
`<script style='text/javascript' src='/pdw-assets/pdw.js'></script>`

**Comment by Zazza** [comment]
yes, with "assets" it is necessary to change something, for example, I use requirejs and I don't need excess files, for example - jquery.
In an ideal, I would clean all libraries.
I will think that it is possible to make.

**Comment by Zazza** [comment]
Update:
[script style='text/javascript' src='/pdw-assets/pdw.js][/script] - it isn't necessary any more. I removed all assets
